### ISSUE TITLE
如何一键补报？

### ISSUE THREAD

**Issue by ghy861918226** [BlueFisher/SHU-selfreport#70]
请问如何一键补报？

**Comment by BlueFisher** [comment]
将main.py中第[23行](https://github.com/BlueFisher/SHU-selfreport/blob/7c6a5cc684789f799194f13995b01e27e0d23153/main.py#L23)设置为 `True`，
将main.py中第[24行](https://github.com/BlueFisher/SHU-selfreport/blob/7c6a5cc684789f799194f13995b01e27e0d23153/main.py#L24)设置为你想开始补报的日期

**Comment by ghy861918226** [comment]
按照您的建议，我改过了True+填报日期，但是这一步不知道哪里有问题，麻烦帮忙看看。
Run python -u main.py
  python -u main.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.1[2](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:3).8.12/x6[4](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:4)/lib
    ovpn_username: ***
    ovpn_password: ***
    users: ***
=====0338=====
Traceback (most recent call last):
  File "main.py", line 321, in <module>
    browser = webdriver.Chrome(options=chrome_options, service=s)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 42[5](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:5), in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.8.12/x[6](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:6)4/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 24[7](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:7), in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 99
Current browser version is 9[8](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:8).0.4758.102 with binary path /usr/bin/google-chrome
Stacktrace:
#0 0x55d32fb607d3 <unknown>
#1 0x55d32f8bc688 <unknown>
#2 0x55d32f8e36a0 <unknown>
#3 0x55d32f8dee36 <unknown>
#4 0x55d32f8db68f <unknown>
#5 0x55d32f[9](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:9)16355 <unknown>
#6 0x55d32f9[10](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:10)5a3 <unknown>
#7 0x55d32f8e5ddc <unknown>
#8 0x55d32f8e6de5 <unknown>
#9 0x55d32fb9149d <unknown>
#10 0x55d32fbaa60c <unknown>
#[11](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:11) 0x55d32fb93205 <unknown>
#[12](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:12) 0x55d32fbaaee5 <unknown>
#[13](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:13) 0x55d32fb87070 <unknown>
#[14](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:14) 0x55d32fbc6488 <unknown>
#[15](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:15) 0x55d32fbc660c <unknown>
#[16](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:16) 0x55d32fbdfc6d <unknown>
#[17](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:17) 0x7f8c0[26](https://github.com/ghy861918226/SHU-selfreport/runs/5511394020?check_suite_focus=true#step:10:26)bc609 <unknown>

Error: Process completed with exit code 1.

**Comment by BlueFisher** [comment]
需要更新一下最新的 https://github.com/BlueFisher/SHU-selfreport/commit/2546d6a53749e826136a669c248769dfe80cc030 因为ChromeDriver版本过期了
